/* Generated by scripts/themes/bauhaus/build-numerals.mjs. Do not hand-edit. */
/* Constructed numerals, module S=20, cell 60x100. */
export interface NumeralPart { kind: 'bar' | 'ring' | 'half' | 'quad'; axis?: 'h' | 'v'; d: string }
export const NUMERAL_PARTS: Record<string, readonly NumeralPart[]> = {
  '0': [
    { kind: 'half', d: 'M0 34L0 30A30 30 0 0 1 60 30L60 34L40 34L40 30A10 10 0 0 0 20 30L20 34Z' },
    { kind: 'bar', axis: 'v', d: 'M0 30h20v40h-20Z' },
    { kind: 'bar', axis: 'v', d: 'M40 30h20v40h-20Z' },
    { kind: 'half', d: 'M60 66L60 70A30 30 0 0 1 0 70L0 66L20 66L20 70A10 10 0 0 0 40 70L40 66Z' },
  ],
  '1': [
    { kind: 'bar', axis: 'v', d: 'M40 0h20v100h-20Z' },
    { kind: 'quad', d: 'M10 30A30 30 0 0 1 40 0L44 0L44 20L40 20A10 10 0 0 0 30 30Z' },
  ],
  '2': [
    { kind: 'half', d: 'M0 30A30 30 0 1 1 59.344 36.237L39.781 32.079A10 10 0 1 0 20 30Z' },
    { kind: 'quad', d: 'M60 30A30 30 0 0 1 30 60L26 60L26 40L30 40A10 10 0 0 0 40 30Z' },
    { kind: 'bar', axis: 'h', d: 'M0 40h31v20h-31Z' },
    { kind: 'bar', axis: 'v', d: 'M0 40h20v60h-20Z' },
    { kind: 'bar', axis: 'h', d: 'M0 80h60v20h-60Z' },
  ],
  '3': [
    { kind: 'half', d: 'M0 30A30 30 0 1 1 59.344 36.237L39.781 32.079A10 10 0 1 0 20 30Z' },
    { kind: 'quad', d: 'M60 30A30 30 0 0 1 30 60L30 40A10 10 0 0 0 40 30Z' },
    { kind: 'quad', d: 'M30 40A30 30 0 0 1 59.344 76.237L39.781 72.079A10 10 0 0 0 30 60Z' },
    { kind: 'half', d: 'M60 70A30 30 0 0 1 0 70L20 70A10 10 0 0 0 40 70Z' },
  ],
  '4': [
    { kind: 'bar', axis: 'v', d: 'M0 0h20v60h-20Z' },
    { kind: 'bar', axis: 'h', d: 'M0 40h60v20h-60Z' },
    { kind: 'bar', axis: 'v', d: 'M40 0h20v100h-20Z' },
  ],
  '5': [
    { kind: 'bar', axis: 'h', d: 'M0 0h60v20h-60Z' },
    { kind: 'bar', axis: 'v', d: 'M0 0h20v60h-20Z' },
    { kind: 'bar', axis: 'h', d: 'M0 40h31v20h-31Z' },
    { kind: 'quad', d: 'M26 40L30 40A30 30 0 0 1 59.344 76.237L39.781 72.079A10 10 0 0 0 30 60L26 60Z' },
    { kind: 'half', d: 'M60 70A30 30 0 0 1 0 70L20 70A10 10 0 0 0 40 70Z' },
  ],
  '6': [
    { kind: 'quad', d: 'M0 34L0 30A30 30 0 0 1 30 0L30 20A10 10 0 0 0 20 30L20 34Z' },
    { kind: 'bar', axis: 'v', d: 'M0 30h20v40h-20Z' },
    { kind: 'ring', d: 'M0 70A30 30 0 1 0 60 70A30 30 0 1 0 0 70ZM20 70A10 10 0 1 1 40 70A10 10 0 1 1 20 70Z' },
  ],
  '7': [
    { kind: 'bar', axis: 'h', d: 'M0 0h31v20h-31Z' },
    { kind: 'quad', d: 'M26 0L30 0A30 30 0 0 1 60 30L60 34L40 34L40 30A10 10 0 0 0 30 20L26 20Z' },
    { kind: 'bar', axis: 'v', d: 'M40 30h20v70h-20Z' },
  ],
  '8': [
    { kind: 'ring', d: 'M0 30A30 30 0 1 0 60 30A30 30 0 1 0 0 30ZM20 30A10 10 0 1 1 40 30A10 10 0 1 1 20 30Z' },
    { kind: 'ring', d: 'M0 70A30 30 0 1 0 60 70A30 30 0 1 0 0 70ZM20 70A10 10 0 1 1 40 70A10 10 0 1 1 20 70Z' },
  ],
  '9': [
    { kind: 'ring', d: 'M0 30A30 30 0 1 0 60 30A30 30 0 1 0 0 30ZM20 30A10 10 0 1 1 40 30A10 10 0 1 1 20 30Z' },
    { kind: 'bar', axis: 'v', d: 'M40 30h20v40h-20Z' },
    { kind: 'quad', d: 'M60 66L60 70A30 30 0 0 1 30 100L30 80A10 10 0 0 0 40 70L40 66Z' },
  ],
};
